import { useEffect, useId, useState, type FormEvent, type ReactNode } from "react";
import { usePreferences } from "../theme/ThemeContext";
import { formatDate, gregorianToJalali, jalaliToGregorian } from "../utils/date";
import { formatMoney, statusLabel } from "../utils/format";

export function PageHeader({ title, description, action }: { title: string; description?: ReactNode; action?: ReactNode }) { return <header className="page-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</header>; }
export function Card({ title, children, className = "" }: { title?: string; children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{title && <h2 className="card-title">{title}</h2>}{children}</section>; }
export function LoadingState({ label = "در حال دریافت اطلاعات…" }: { label?: string }) { return <div className="state" role="status"><span className="spinner" />{label}</div>; }
export function EmptyState({ title = "اطلاعاتی ثبت نشده است", detail }: { title?: string; detail?: string }) { return <div className="state state--empty"><span className="state-icon" aria-hidden>□</span><strong>{title}</strong>{detail && <small>{detail}</small>}</div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="state state--error" role="alert"><strong>دریافت اطلاعات ناموفق بود</strong><span>{message}</span>{retry && <button className="button button--secondary" onClick={retry}>تلاش دوباره</button>}</div>; }
export function StatusBadge({ value }: { value: string }) { const danger = ["CANCELLED", "OVERDUE", "HIGH", "INACTIVE"].includes(value.toUpperCase()); const warn = ["DRAFT", "PARTIALLY_PAID", "MEDIUM"].includes(value.toUpperCase()); return <span className={`badge ${danger ? "badge--danger" : warn ? "badge--warning" : "badge--success"}`}>{statusLabel(value)}</span>; }
export function Money({ value, suffix = "ریال" }: { value: string | number; suffix?: string }) { return <span className={Number(value) < 0 ? "negative money" : "money"} dir="ltr">{formatMoney(value)} <small>{suffix}</small></span>; }
export function DateText({ value }: { value: string | null | undefined }) { const { calendar } = usePreferences(); return <time dateTime={value ?? undefined} dir="ltr">{formatDate(value, calendar)}</time>; }
export function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) { return <label className={`field ${error ? "field--error" : ""}`}><span>{label}</span>{children}{hint && <small>{hint}</small>}{error && <small role="alert">{error}</small>}</label>; }
export function DateField({ label, value, onChange, required }: { label: string; value: string; onChange: (iso: string) => void; required?: boolean }) { const { calendar } = usePreferences(); const [text, setText] = useState(calendar === "jalali" && value ? gregorianToJalali(value) : value); const [error, setError] = useState(""); useEffect(() => setText(calendar === "jalali" && value ? gregorianToJalali(value) : value), [calendar, value]);
  const change = (next: string) => { setText(next); setError(""); if (calendar === "gregorian") { onChange(next); return; } try { if (next.length >= 8) onChange(jalaliToGregorian(next)); } catch (reason) { setError(reason instanceof Error ? reason.message : "تاریخ نامعتبر است."); } };
  return <Field label={`${label} (${calendar === "jalali" ? "شمسی" : "میلادی"})`} error={error}><input type={calendar === "gregorian" ? "date" : "text"} dir="ltr" placeholder={calendar === "jalali" ? "1405/01/01" : undefined} value={text} onChange={(e) => change(e.target.value)} required={required} /></Field>;
}
export function Modal({ open, title, children, onClose, wide = false }: { open: boolean; title: string; children: ReactNode; onClose: () => void; wide?: boolean }) { const titleId = useId(); useEffect(() => { if (!open) return; const key = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [open, onClose]); if (!open) return null; return <div className="modal-backdrop" onMouseDown={(e) => { if (e.currentTarget === e.target) onClose(); }}><section className={`modal ${wide ? "modal--wide" : ""}`} role="dialog" aria-modal="true" aria-labelledby={titleId}><header><h2 id={titleId}>{title}</h2><button className="icon-button" onClick={onClose} aria-label="بستن">×</button></header>{children}</section></div>; }
export function Confirm({ open, title, message, confirmLabel, onConfirm, onClose, busy }: { open: boolean; title: string; message: string; confirmLabel: string; onConfirm: () => void; onClose: () => void; busy?: boolean }) { return <Modal open={open} title={title} onClose={onClose}><p>{message}</p><div className="form-actions"><button className="button button--secondary" onClick={onClose}>انصراف</button><button className="button button--danger" disabled={busy} onClick={onConfirm}>{busy ? "در حال انجام…" : confirmLabel}</button></div></Modal>; }
export function SubmitForm({ children, onSubmit, className = "" }: { children: ReactNode; onSubmit: (event: FormEvent<HTMLFormElement>) => void; className?: string }) { return <form className={`form ${className}`} onSubmit={onSubmit}>{children}</form>; }
