"""stage 3 accounting vertical slice

Revision ID: cd6670d77e70
Revises: 20260817_0001
Create Date: 2026-08-18 15:33:17.041083
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "cd6670d77e70"
down_revision: str | None = "20260817_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')",
            name=op.f("ck_account_categories_valid_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_categories")),
        sa.UniqueConstraint("name", name="uq_account_categories_name"),
    )
    op.create_table(
        "financial_periods",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="OPEN", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','CLOSED')", name=op.f("ck_financial_periods_valid_status")
        ),
        sa.CheckConstraint("start_date <= end_date", name=op.f("ck_financial_periods_valid_dates")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_periods")),
        sa.UniqueConstraint("name", name="uq_financial_periods_name"),
    )
    op.create_index(
        op.f("ix_financial_periods_end_date"), "financial_periods", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_financial_periods_start_date"), "financial_periods", ["start_date"], unique=False
    )
    op.create_table(
        "parties",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_customer", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_supplier", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("is_customer OR is_supplier", name=op.f("ck_parties_has_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parties")),
    )
    op.create_index(op.f("ix_parties_name"), "parties", ["name"], unique=False)
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=30), server_default="each", nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_products_nonnegative_price")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name="uq_products_sku"),
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_accounts_not_own_parent")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["account_categories.id"],
            name=op.f("fk_accounts_category_id_account_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["accounts.id"], name=op.f("fk_accounts_parent_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("code", name="uq_accounts_code"),
    )
    op.create_index(op.f("ix_accounts_code"), "accounts", ["code"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("entry_number", sa.String(length=80), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="DRAFT", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','POSTED','CANCELLED')", name=op.f("ck_journal_entries_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_journal_entries_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["financial_periods.id"],
            name=op.f("fk_journal_entries_period_id_financial_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_entries_reversal_of_id_journal_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
        sa.UniqueConstraint("entry_number", name="uq_journal_entries_entry_number"),
        sa.UniqueConstraint("reversal_of_id", name=op.f("uq_journal_entries_reversal_of_id")),
    )
    op.create_index(
        op.f("ix_journal_entries_entry_date"), "journal_entries", ["entry_date"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_entry_number"), "journal_entries", ["entry_number"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("invoice_number", sa.String(length=80), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column(
            "subtotal", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("tax", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column(
            "amount_paid", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("journal_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ISSUED','PARTIALLY_PAID','PAID','CANCELLED')",
            name=op.f("ck_invoices_valid_status"),
        ),
        sa.CheckConstraint("issue_date <= due_date", name=op.f("ck_invoices_valid_dates")),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax >= 0 AND total >= 0 AND amount_paid >= 0",
            name=op.f("ck_invoices_nonnegative_totals"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["parties.id"],
            name=op.f("fk_invoices_customer_id_parties"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journal_entries.id"],
            name=op.f("fk_invoices_journal_id_journal_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("invoice_number", name="uq_invoices_invoice_number"),
        sa.UniqueConstraint("journal_id", name=op.f("uq_invoices_journal_id")),
    )
    op.create_index(
        op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=False
    )
    op.create_table(
        "journal_lines",
        sa.Column("journal_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("debit", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)",
            name=op.f("ck_journal_lines_one_positive_side"),
        ),
        sa.CheckConstraint(
            "debit >= 0 AND credit >= 0", name=op.f("ck_journal_lines_nonnegative_amounts")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_journal_lines_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_lines_journal_id_journal_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_lines")),
    )
    op.create_table(
        "payments",
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="DRAFT", nullable=False),
        sa.Column("journal_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','POSTED','CANCELLED')", name=op.f("ck_payments_valid_status")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_positive_amount")),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journal_entries.id"],
            name=op.f("fk_payments_journal_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["parties.id"],
            name=op.f("fk_payments_party_id_parties"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("journal_id", name=op.f("uq_payments_journal_id")),
        sa.UniqueConstraint("reference", name="uq_payments_reference"),
    )
    op.create_index(op.f("ix_payments_reference"), "payments", ["reference"], unique=False)
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("line_subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_invoice_items_positive_quantity")),
        sa.CheckConstraint(
            "unit_price >= 0 AND tax >= 0 AND line_subtotal >= 0 AND line_total >= 0",
            name=op.f("ck_invoice_items_nonnegative_totals"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_items_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_invoice_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_items")),
    )
    op.create_table(
        "payment_allocations",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payment_allocations_positive_amount")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payment_allocations_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_allocations_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_allocations")),
        sa.UniqueConstraint("payment_id", "invoice_id", name="uq_payment_allocations_pair"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_allocations")
    op.drop_table("invoice_items")
    op.drop_index(op.f("ix_payments_reference"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("journal_lines")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_journal_entries_entry_number"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_entry_date"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_accounts_code"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_parties_name"), table_name="parties")
    op.drop_table("parties")
    op.drop_index(op.f("ix_financial_periods_start_date"), table_name="financial_periods")
    op.drop_index(op.f("ix_financial_periods_end_date"), table_name="financial_periods")
    op.drop_table("financial_periods")
    op.drop_table("account_categories")
    # ### end Alembic commands ###
