import { Card, DateText, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from "../components/ui";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/api";
import { usePreferences } from "../theme/ThemeContext";
import type { User } from "../types/api";
const roleLabels: Record<string, string> = { ADMIN: "مدیر سامانه", ACCOUNTANT: "حسابدار", MANAGER: "مدیر", VIEWER: "مشاهده‌گر" };
export function UsersPage() { const state = useAsync(() => api.get<User[]>("/users"), []); return <><PageHeader title="کاربران" description="فهرست کاربران و نقش‌های دسترسی"/>{state.loading ? <LoadingState/> : state.error ? <ErrorState message={state.error} retry={state.reload}/> : state.data?.length ? <div className="table-wrap"><table><thead><tr><th>نام</th><th>ایمیل</th><th>نقش</th><th>آخرین ورود</th><th>وضعیت</th></tr></thead><tbody>{state.data.map((u) => <tr key={u.id}><td><strong>{u.first_name} {u.last_name}</strong></td><td dir="ltr">{u.email}</td><td>{u.roles.map((r) => roleLabels[r] ?? r).join("، ")}</td><td><DateText value={u.last_login_at}/></td><td><StatusBadge value={u.is_active ? "ACTIVE" : "INACTIVE"}/></td></tr>)}</tbody></table></div> : <EmptyState title="کاربری وجود ندارد"/>}<div className="alert alert--info">API فعلی فقط مشاهده کاربران را پشتیبانی می‌کند؛ تغییر نقش یا ساخت کاربر مدیریتی از این صفحه انجام نمی‌شود.</div></>;
}
export function SettingsPage() { const { theme, calendar, toggleTheme, setCalendar } = usePreferences(); return <><PageHeader title="تنظیمات نمایش" description="انتخاب ظاهر و تقویم دلخواه شما"/><div className="settings-grid"><Card title="رنگ‌بندی"><p>حالت روشن به‌طور پیش‌فرض فعال است. انتخاب شما در همین مرورگر ذخیره می‌شود.</p><div className="choice-row"><button className={`theme-choice ${theme === "light" ? "selected" : ""}`} onClick={() => theme === "dark" && toggleTheme()}><span className="theme-preview light"/>روشن</button><button className={`theme-choice ${theme === "dark" ? "selected" : ""}`} onClick={() => theme === "light" && toggleTheme()}><span className="theme-preview dark"/>تاریک</button></div></Card><Card title="تقویم"><p>ورودی و نمایش تاریخ می‌تواند شمسی یا میلادی باشد. داده‌ها همیشه با تاریخ میلادی استاندارد به سرور ارسال می‌شوند.</p><div className="choice-row"><button className={`calendar-choice ${calendar === "jalali" ? "selected" : ""}`} onClick={() => setCalendar("jalali")}><strong dir="ltr">1405/06/03</strong><span>تقویم شمسی</span></button><button className={`calendar-choice ${calendar === "gregorian" ? "selected" : ""}`} onClick={() => setCalendar("gregorian")}><strong dir="ltr">2026-08-25</strong><span>تقویم میلادی</span></button></div></Card></div></>;
}
