import { useMemo } from "react";
import { useAuth } from "../auth/AuthContext";
import { MiniBars } from "../components/charts";
import { Card, DateText, EmptyState, ErrorState, LoadingState, Money, PageHeader, StatusBadge } from "../components/ui";
import { useAsync } from "../hooks/useAsync";
import { api } from "../services/api";
import type { CashFlow, DashboardReport, Invoice, Payment, Prediction } from "../types/api";
import { formatDate } from "../utils/date";
import { PIPELINE_LABELS } from "../utils/format";
import { Link } from "../routes/router";

export function DashboardPage() { const { user, can } = useAuth(); const state = useAsync(async () => { const [dashboard, cash, invoices, payments, predictions] = await Promise.all([api.get<DashboardReport>("/dashboard"), api.get<CashFlow>("/reports/cash-flow"), can("invoices:read") ? api.get<Invoice[]>("/invoices") : Promise.resolve([]), can("payments:read") ? api.get<Payment[]>("/payments") : Promise.resolve([]), can("ml:read") ? api.get<Prediction[]>("/ml/predictions") : Promise.resolve([])]); return { dashboard, cash, invoices, payments, predictions }; }, [can]);
  const chart = useMemo(() => state.data?.cash.points.map((p) => ({ label: formatDate(p.date), value: Number(p.inflow), secondary: Number(p.outflow) })) ?? [], [state.data]);
  if (state.loading) return <LoadingState label="در حال آماده‌سازی داشبورد…" />; if (state.error || !state.data) return <ErrorState message={state.error} retry={state.reload} />; const { dashboard: d } = state.data;
  return <><PageHeader title={`سلام ${user?.first_name ?? ""}، روز خوبی داشته باشید`} description={<>نمای کلی کسب‌وکار تا تاریخ <DateText value={d.as_of} /></>} action={can("invoices:write") ? <Link to="/invoices" className="button button--primary">ثبت فاکتور جدید</Link> : undefined} /><section className="kpi-grid"><Kpi title="درآمد" value={d.total_revenue} tone="positive"/><Kpi title="هزینه" value={d.total_expenses}/><Kpi title="سود خالص" value={d.net_income} tone={Number(d.net_income) >= 0 ? "positive" : "negative"}/><Kpi title="جریان نقدی خالص" value={d.net_cash_flow}/><Kpi title="مانده مطالبات" value={d.outstanding_invoices} note={`${d.outstanding_invoice_count} فاکتور`}/><Kpi title="مطالبات سررسیدگذشته" value={d.overdue_invoices} note={`${d.overdue_invoice_count} فاکتور`} tone={Number(d.overdue_invoices) > 0 ? "negative" : "positive"}/></section><section className="dashboard-grid"><Card title="روند دریافت و پرداخت" className="span-2"><div className="chart-legend"><span><i className="legend-inflow"/>دریافت</span><span><i className="legend-outflow"/>پرداخت</span></div><MiniBars data={chart}/></Card><Card title="پیگیری فوری"><div className="attention"><strong>{d.overdue_invoice_count}</strong><span>فاکتور سررسیدگذشته</span><Money value={d.overdue_invoices}/><Link to="/reports/receivables">مشاهده مطالبات ←</Link></div></Card><RecentInvoices items={state.data.invoices.slice(-5).reverse()} /><RecentPayments items={state.data.payments.slice(-5).reverse()} /><AiActivity items={state.data.predictions.slice(0, 5)} /></section></>;
}
export function Kpi({ title, value, note, tone = "" }: { title: string; value: string; note?: string; tone?: string }) { return <article className={`kpi ${tone}`}><span>{title}</span><Money value={value}/>{note && <small>{note}</small>}</article>; }
function RecentInvoices({ items }: { items: Invoice[] }) { return <Card title="آخرین فاکتورها">{items.length ? <div className="compact-list">{items.map((x) => <Link key={x.id} to="/invoices"><span><strong>{x.invoice_number}</strong><small><DateText value={x.issue_date}/></small></span><span><Money value={x.total}/><StatusBadge value={x.status}/></span></Link>)}</div> : <EmptyState title="فاکتوری ثبت نشده است"/>}</Card>; }
function RecentPayments({ items }: { items: Payment[] }) { return <Card title="آخرین دریافت‌ها">{items.length ? <div className="compact-list">{items.map((x) => <Link key={x.id} to="/payments"><span><strong>{x.reference}</strong><small><DateText value={x.payment_date}/></small></span><span><Money value={x.amount}/><StatusBadge value={x.status}/></span></Link>)}</div> : <EmptyState title="پرداختی ثبت نشده است"/>}</Card>; }
function AiActivity({ items }: { items: Prediction[] }) { return <Card title="فعالیت هوش مصنوعی">{items.length ? <div className="compact-list">{items.map((x) => <Link key={x.id} to="/ai"><span><strong>{PIPELINE_LABELS[x.pipeline]}</strong><small><DateText value={x.predicted_at}/></small></span>{x.review_required && <span className="badge badge--warning">نیازمند بررسی</span>}</Link>)}</div> : <EmptyState title="تحلیلی انجام نشده است" detail="پس از اجرای مدل‌ها، نتایج اینجا دیده می‌شوند."/>}</Card>; }
