import { useState, type ReactNode } from "react";
import { MiniBars, TrendLine } from "../components/charts";
import { Card, DateField, DateText, EmptyState, ErrorState, LoadingState, Money, PageHeader, StatusBadge } from "../components/ui";
import { useAsync } from "../hooks/useAsync";
import { useRouter } from "../routes/router";
import { api, query } from "../services/api";
import type { AccountReportLine, AccountSummary, BalanceSheet, CashFlow, IncomeStatement, Party, PartyHistory, Payables, Receivables, TrialBalance } from "../types/api";
import { ACCOUNT_TYPE_LABELS } from "../utils/format";
import { todayIso } from "../utils/date";

const titles: Record<string, string> = { "trial-balance": "تراز آزمایشی", "income-statement": "صورت سود و زیان", "balance-sheet": "ترازنامه", revenue: "گزارش درآمدها", expenses: "گزارش هزینه‌ها", receivables: "گزارش مطالبات", payables: "گزارش پرداختنی‌ها", "cash-flow": "گزارش جریان نقدی", "party-history": "گردش طرف حساب" };
type ReportKind = keyof typeof titles;
export function ReportsPage() { const { path } = useRouter(); const kind = path.split("/").pop() as ReportKind; const [filters, setFilters] = useState({ start: "", end: "", asOf: todayIso(), party: "" }); const state = useAsync(async () => {
  if (kind === "party-history") { const parties = await api.get<Party[]>("/parties"); if (!filters.party) return { parties, report: null }; return { parties, report: await api.get<PartyHistory>(query(`/reports/parties/${filters.party}/history`, { start_date: filters.start, end_date: filters.end })) }; }
  if (kind === "trial-balance") return api.get<TrialBalance>(query("/reports/trial-balance", { start_date: filters.start, end_date: filters.end }));
  if (kind === "income-statement") return api.get<IncomeStatement>(query("/reports/income-statement", { start_date: filters.start, end_date: filters.end }));
  if (kind === "revenue" || kind === "expenses") return api.get<AccountSummary>(query(`/reports/${kind}`, { start_date: filters.start, end_date: filters.end }));
  if (kind === "balance-sheet") return api.get<BalanceSheet>(query("/reports/balance-sheet", { as_of: filters.asOf }));
  if (kind === "receivables") { const [parties, report] = await Promise.all([api.get<Party[]>("/parties"), api.get<Receivables>(query("/reports/receivables", { as_of: filters.asOf, customer_id: filters.party }))]); return { parties, report }; }
  if (kind === "payables") return api.get<Payables>(query("/reports/payables", { as_of: filters.asOf }));
  return api.get<CashFlow>(query("/reports/cash-flow", { start_date: filters.start, end_date: filters.end }));
 }, [kind, filters.start, filters.end, filters.asOf, filters.party]);
 const asOf = ["balance-sheet", "receivables", "payables"].includes(kind); const withParty = ["receivables", "party-history"].includes(kind); const parties = withParty && state.data && "parties" in state.data ? state.data.parties : [];
 return <><PageHeader title={titles[kind] ?? "گزارش"} description="تمام مبالغ از اسناد ثبت‌شده در سامانه محاسبه شده‌اند." action={<button className="button button--secondary print-hide" onClick={() => print()}>چاپ گزارش</button>}/><Card className="report-filters"><div className="filter-row">{asOf ? <DateField label="تا تاریخ" value={filters.asOf} onChange={(asOfValue) => setFilters((f) => ({ ...f, asOf: asOfValue }))}/> : <><DateField label="از تاریخ" value={filters.start} onChange={(start) => setFilters((f) => ({ ...f, start }))}/><DateField label="تا تاریخ" value={filters.end} onChange={(end) => setFilters((f) => ({ ...f, end }))}/></>}{withParty && <label className="field"><span>طرف حساب</span><select value={filters.party} onChange={(e) => setFilters((f) => ({ ...f, party: e.target.value }))}><option value="">{kind === "party-history" ? "انتخاب کنید" : "همه مشتریان"}</option>{parties.filter((p: Party) => p.is_customer).map((p: Party) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}</div></Card>{state.loading ? <LoadingState label="در حال محاسبه گزارش…"/> : state.error ? <ErrorState message={state.error} retry={state.reload}/> : <ReportResult kind={kind} data={state.data}/>}</>;
}
function AccountLines({ lines }: { lines: AccountReportLine[] }) { if (!lines.length) return <EmptyState title="در این بازه گردش مالی وجود ندارد"/>; return <div className="table-wrap"><table><thead><tr><th>کد حساب</th><th>نام حساب</th><th>نوع حساب</th><th>بدهکار</th><th>بستانکار</th><th>مانده</th></tr></thead><tbody>{lines.map((x) => <tr key={x.account_id}><td data-label="کد حساب" dir="ltr">{x.code}</td><td data-label="نام حساب"><strong>{x.name}</strong></td><td data-label="نوع حساب">{ACCOUNT_TYPE_LABELS[x.account_type] ?? x.account_type}</td><td data-label="بدهکار"><Money value={x.debit}/></td><td data-label="بستانکار"><Money value={x.credit}/></td><td data-label="مانده"><Money value={x.balance}/></td></tr>)}</tbody></table></div>; }
function Summary({ children }: { children: ReactNode }) { return <div className="report-summary">{children}</div>; }
export function ReportResult({ kind, data }: { kind: ReportKind; data: unknown }) {
  if (kind === "trial-balance") { const r = data as TrialBalance; return <Card><AccountLines lines={r.lines}/><Summary><span>جمع بدهکار <Money value={r.total_debit}/></span><span>جمع بستانکار <Money value={r.total_credit}/></span><StatusBadge value={r.balanced ? "POSTED" : "HIGH"}/></Summary></Card>; }
  if (kind === "income-statement") { const r = data as IncomeStatement; return <><section className="kpi-grid kpi-grid--3"><Kpi label="درآمد" value={r.total_revenue}/><Kpi label="هزینه" value={r.total_expenses}/><Kpi label="سود خالص" value={r.net_income}/></section><div className="split"><Card title="درآمدها"><AccountLines lines={r.revenue}/></Card><Card title="هزینه‌ها"><AccountLines lines={r.expenses}/></Card></div></>; }
  if (kind === "revenue" || kind === "expenses") { const r = data as AccountSummary; return <><section className="kpi-grid kpi-grid--1"><Kpi label="جمع گزارش" value={r.total}/></section><Card><AccountLines lines={r.lines}/></Card></>; }
  if (kind === "balance-sheet") { const r = data as BalanceSheet; return <><section className="kpi-grid kpi-grid--3"><Kpi label="جمع دارایی" value={r.total_assets}/><Kpi label="بدهی و حقوق مالکانه" value={r.total_liabilities_and_equity}/><Kpi label="سود جاری" value={r.current_earnings}/></section><div className="split"><Card title="دارایی‌ها"><AccountLines lines={r.assets}/></Card><Card title="بدهی‌ها"><AccountLines lines={r.liabilities}/></Card></div><Card title="حقوق مالکانه"><AccountLines lines={r.equity}/></Card></>; }
  if (kind === "receivables") { const r = (data as { report: Receivables }).report; return <><section className="kpi-grid kpi-grid--2"><Kpi label="جمع مطالبات" value={r.total_outstanding}/><Kpi label="سررسیدگذشته" value={r.total_overdue}/></section><Card>{r.lines.length ? <div className="table-wrap"><table><thead><tr><th>فاکتور</th><th>مشتری</th><th>سررسید</th><th>کل</th><th>پرداخت‌شده</th><th>مانده</th><th>تأخیر</th></tr></thead><tbody>{r.lines.map((x) => <tr key={x.invoice_id}><td data-label="فاکتور" dir="ltr">{x.invoice_number}</td><td data-label="مشتری">{x.customer_name}</td><td data-label="سررسید"><DateText value={x.due_date}/></td><td data-label="کل"><Money value={x.total}/></td><td data-label="پرداخت‌شده"><Money value={x.amount_paid}/></td><td data-label="مانده"><Money value={x.balance_due}/></td><td data-label="تأخیر" className={x.days_overdue > 0 ? "negative" : ""}>{x.days_overdue > 0 ? `${x.days_overdue} روز` : "بدون تأخیر"}</td></tr>)}</tbody></table></div> : <EmptyState title="مطالبه بازی وجود ندارد"/>}</Card></>; }
  if (kind === "payables") { const r = data as Payables; return <><section className="kpi-grid kpi-grid--1"><Kpi label="مانده حساب‌های پرداختنی" value={r.total_payables}/></section>{!r.supplier_detail_available && <div className="alert alert--info">جزئیات پرداختنی به تفکیک تأمین‌کننده در مدل فعلی حسابداری موجود نیست؛ این گزارش مانده حساب‌های بدهی ثبت‌شده را نشان می‌دهد.</div>}<Card><AccountLines lines={r.lines}/></Card></>; }
  if (kind === "cash-flow") { const r = data as CashFlow; return <><section className="kpi-grid kpi-grid--3"><Kpi label="ورودی نقدی" value={r.total_inflow}/><Kpi label="خروجی نقدی" value={r.total_outflow}/><Kpi label="خالص جریان نقدی" value={r.net_cash_flow}/></section><Card title="روند جریان نقدی"><TrendLine data={r.points.map((x) => ({ label: x.date, value: Number(x.net) }))}/></Card><Card><div className="table-wrap"><table><thead><tr><th>تاریخ</th><th>ورودی</th><th>خروجی</th><th>خالص</th></tr></thead><tbody>{r.points.map((x) => <tr key={x.date}><td data-label="تاریخ"><DateText value={x.date}/></td><td data-label="ورودی"><Money value={x.inflow}/></td><td data-label="خروجی"><Money value={x.outflow}/></td><td data-label="خالص"><Money value={x.net}/></td></tr>)}</tbody></table></div></Card></>; }
  const wrapped = data as { report: PartyHistory | null }; if (!wrapped.report) return <EmptyState title="یک طرف حساب انتخاب کنید" detail="پس از انتخاب، گردش فاکتورها و پرداخت‌های او نمایش داده می‌شود."/>; const r = wrapped.report; return <Card title={`گردش ${r.party_name}`}>{r.transactions.length ? <div className="table-wrap"><table><thead><tr><th>نوع</th><th>مرجع</th><th>تاریخ</th><th>مبلغ</th><th>وضعیت</th></tr></thead><tbody>{r.transactions.map((x) => <tr key={x.record_id}><td data-label="نوع">{x.kind === "INVOICE" ? "فاکتور" : "پرداخت"}</td><td data-label="مرجع" dir="ltr">{x.reference}</td><td data-label="تاریخ"><DateText value={x.date}/></td><td data-label="مبلغ"><Money value={x.amount}/></td><td data-label="وضعیت"><StatusBadge value={x.status}/></td></tr>)}</tbody></table></div> : <EmptyState title="گردشی در این بازه وجود ندارد"/>}</Card>;
}
function Kpi({ label, value }: { label: string; value: string }) { return <article className="kpi"><span>{label}</span><Money value={value}/></article>; }
