import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/vazirmatn/400.css";
import "@fontsource/vazirmatn/500.css";
import "@fontsource/vazirmatn/600.css";
import "@fontsource/vazirmatn/700.css";
import "@fontsource/vazirmatn/800.css";
import App from "./App";
import { AuthProvider } from "./auth/AuthContext";
import { RouterProvider } from "./routes/router";
import { ThemeProvider } from "./theme/ThemeContext";
createRoot(document.getElementById("root")!).render(<StrictMode><ThemeProvider><RouterProvider><AuthProvider><App/></AuthProvider></RouterProvider></ThemeProvider></StrictMode>);
